//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Stuffs = new HashSet<Stuff>();
        }
    
        public int PostId { get; set; }
        public string PostName { get; set; }
        public int Salary { get; set; }
    
        public virtual ICollection<Stuff> Stuffs { get; set; }
    }
}
