//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.TicketInfoes = new HashSet<TicketInfo>();
        }
    
        public int ScheduleID { get; set; }
        public string PlaceOfDeparture { get; set; }
        public string PlaceOfArrival { get; set; }
        public System.DateTime Date { get; set; }
        public int NumberOfTicketsPurchased { get; set; }
        public int TotalTickets { get; set; }
    
        public virtual ICollection<TicketInfo> TicketInfoes { get; set; }
    }
}
