//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stuff
    {
        public Stuff()
        {
            this.ApplicationForTheConditionOfTheAircrafts = new HashSet<ApplicationForTheConditionOfTheAircraft>();
        }
    
        public int StuffID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.DateTime BirthdayDate { get; set; }
    
        public virtual ICollection<ApplicationForTheConditionOfTheAircraft> ApplicationForTheConditionOfTheAircrafts { get; set; }
        public virtual Post Post { get; set; }
    }
}
